// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: authzed/api/materialize/v0/brokensets_service.proto

package v0

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ReadBrokenSetsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ReadBrokenSetsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ReadBrokenSetsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ReadBrokenSetsRequestMultiError, or nil if none found.
func (m *ReadBrokenSetsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ReadBrokenSetsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for BatchSize

	if all {
		switch v := interface{}(m.GetOptionalAtRevision()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ReadBrokenSetsRequestValidationError{
					field:  "OptionalAtRevision",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ReadBrokenSetsRequestValidationError{
					field:  "OptionalAtRevision",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetOptionalAtRevision()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ReadBrokenSetsRequestValidationError{
				field:  "OptionalAtRevision",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ReadBrokenSetsRequestMultiError(errors)
	}

	return nil
}

// ReadBrokenSetsRequestMultiError is an error wrapping multiple validation
// errors returned by ReadBrokenSetsRequest.ValidateAll() if the designated
// constraints aren't met.
type ReadBrokenSetsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ReadBrokenSetsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ReadBrokenSetsRequestMultiError) AllErrors() []error { return m }

// ReadBrokenSetsRequestValidationError is the validation error returned by
// ReadBrokenSetsRequest.Validate if the designated constraints aren't met.
type ReadBrokenSetsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ReadBrokenSetsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ReadBrokenSetsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ReadBrokenSetsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ReadBrokenSetsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ReadBrokenSetsRequestValidationError) ErrorName() string {
	return "ReadBrokenSetsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ReadBrokenSetsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sReadBrokenSetsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ReadBrokenSetsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ReadBrokenSetsRequestValidationError{}

// Validate checks the field values on BrokenSet with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *BrokenSet) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BrokenSet with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in BrokenSetMultiError, or nil
// if none found.
func (m *BrokenSet) ValidateAll() error {
	return m.validate(true)
}

func (m *BrokenSet) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ResourceType

	// no validation rules for ResourceId

	// no validation rules for Permission

	if len(errors) > 0 {
		return BrokenSetMultiError(errors)
	}

	return nil
}

// BrokenSetMultiError is an error wrapping multiple validation errors returned
// by BrokenSet.ValidateAll() if the designated constraints aren't met.
type BrokenSetMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BrokenSetMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BrokenSetMultiError) AllErrors() []error { return m }

// BrokenSetValidationError is the validation error returned by
// BrokenSet.Validate if the designated constraints aren't met.
type BrokenSetValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BrokenSetValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BrokenSetValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BrokenSetValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BrokenSetValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BrokenSetValidationError) ErrorName() string { return "BrokenSetValidationError" }

// Error satisfies the builtin error interface
func (e BrokenSetValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBrokenSet.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BrokenSetValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BrokenSetValidationError{}

// Validate checks the field values on ReadBrokenSetsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ReadBrokenSetsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ReadBrokenSetsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ReadBrokenSetsResponseMultiError, or nil if none found.
func (m *ReadBrokenSetsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ReadBrokenSetsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetBrokenSets() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ReadBrokenSetsResponseValidationError{
						field:  fmt.Sprintf("BrokenSets[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ReadBrokenSetsResponseValidationError{
						field:  fmt.Sprintf("BrokenSets[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ReadBrokenSetsResponseValidationError{
					field:  fmt.Sprintf("BrokenSets[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if all {
		switch v := interface{}(m.GetRevision()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ReadBrokenSetsResponseValidationError{
					field:  "Revision",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ReadBrokenSetsResponseValidationError{
					field:  "Revision",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetRevision()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ReadBrokenSetsResponseValidationError{
				field:  "Revision",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ReadBrokenSetsResponseMultiError(errors)
	}

	return nil
}

// ReadBrokenSetsResponseMultiError is an error wrapping multiple validation
// errors returned by ReadBrokenSetsResponse.ValidateAll() if the designated
// constraints aren't met.
type ReadBrokenSetsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ReadBrokenSetsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ReadBrokenSetsResponseMultiError) AllErrors() []error { return m }

// ReadBrokenSetsResponseValidationError is the validation error returned by
// ReadBrokenSetsResponse.Validate if the designated constraints aren't met.
type ReadBrokenSetsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ReadBrokenSetsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ReadBrokenSetsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ReadBrokenSetsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ReadBrokenSetsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ReadBrokenSetsResponseValidationError) ErrorName() string {
	return "ReadBrokenSetsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ReadBrokenSetsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sReadBrokenSetsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ReadBrokenSetsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ReadBrokenSetsResponseValidationError{}
