// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: authzed/api/materialize/v0/brokensets_service.proto

package v0

import (
	v1 "github.com/authzed/authzed-go/proto/authzed/api/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReadBrokenSetsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// batch_size specifies the maximum number of broken sets to return in a single response.
	// If set to zero, the server will use the default batch size.
	BatchSize uint32 `protobuf:"varint,1,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	// optional_at_revision defines the specific revision at which the broken sets should be evaluated.
	// At this time, it is only compared against the revision of the provided backing store snapshot.
	OptionalAtRevision *v1.ZedToken `protobuf:"bytes,2,opt,name=optional_at_revision,json=optionalAtRevision,proto3" json:"optional_at_revision,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ReadBrokenSetsRequest) Reset() {
	*x = ReadBrokenSetsRequest{}
	mi := &file_authzed_api_materialize_v0_brokensets_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadBrokenSetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadBrokenSetsRequest) ProtoMessage() {}

func (x *ReadBrokenSetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authzed_api_materialize_v0_brokensets_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadBrokenSetsRequest.ProtoReflect.Descriptor instead.
func (*ReadBrokenSetsRequest) Descriptor() ([]byte, []int) {
	return file_authzed_api_materialize_v0_brokensets_service_proto_rawDescGZIP(), []int{0}
}

func (x *ReadBrokenSetsRequest) GetBatchSize() uint32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

func (x *ReadBrokenSetsRequest) GetOptionalAtRevision() *v1.ZedToken {
	if x != nil {
		return x.OptionalAtRevision
	}
	return nil
}

type BrokenSet struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// resource_type is the type of the broken resource.
	ResourceType string `protobuf:"bytes,1,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	// resource_id is the id of the broken resource.
	ResourceId string `protobuf:"bytes,2,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	// permission is the broken permission set.
	Permission    string `protobuf:"bytes,3,opt,name=permission,proto3" json:"permission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrokenSet) Reset() {
	*x = BrokenSet{}
	mi := &file_authzed_api_materialize_v0_brokensets_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrokenSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrokenSet) ProtoMessage() {}

func (x *BrokenSet) ProtoReflect() protoreflect.Message {
	mi := &file_authzed_api_materialize_v0_brokensets_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrokenSet.ProtoReflect.Descriptor instead.
func (*BrokenSet) Descriptor() ([]byte, []int) {
	return file_authzed_api_materialize_v0_brokensets_service_proto_rawDescGZIP(), []int{1}
}

func (x *BrokenSet) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *BrokenSet) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *BrokenSet) GetPermission() string {
	if x != nil {
		return x.Permission
	}
	return ""
}

type ReadBrokenSetsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// broken_sets contains the list of broken sets found for the requested revision.
	BrokenSets []*BrokenSet `protobuf:"bytes,1,rep,name=broken_sets,json=brokenSets,proto3" json:"broken_sets,omitempty"`
	// read_at is the ZedToken at which the broken set applies.
	Revision      *v1.ZedToken `protobuf:"bytes,2,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadBrokenSetsResponse) Reset() {
	*x = ReadBrokenSetsResponse{}
	mi := &file_authzed_api_materialize_v0_brokensets_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadBrokenSetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadBrokenSetsResponse) ProtoMessage() {}

func (x *ReadBrokenSetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authzed_api_materialize_v0_brokensets_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadBrokenSetsResponse.ProtoReflect.Descriptor instead.
func (*ReadBrokenSetsResponse) Descriptor() ([]byte, []int) {
	return file_authzed_api_materialize_v0_brokensets_service_proto_rawDescGZIP(), []int{2}
}

func (x *ReadBrokenSetsResponse) GetBrokenSets() []*BrokenSet {
	if x != nil {
		return x.BrokenSets
	}
	return nil
}

func (x *ReadBrokenSetsResponse) GetRevision() *v1.ZedToken {
	if x != nil {
		return x.Revision
	}
	return nil
}

var File_authzed_api_materialize_v0_brokensets_service_proto protoreflect.FileDescriptor

const file_authzed_api_materialize_v0_brokensets_service_proto_rawDesc = "" +
	"\n" +
	"3authzed/api/materialize/v0/brokensets_service.proto\x12\x1aauthzed.api.materialize.v0\x1a\x19authzed/api/v1/core.proto\"\x82\x01\n" +
	"\x15ReadBrokenSetsRequest\x12\x1d\n" +
	"\n" +
	"batch_size\x18\x01 \x01(\rR\tbatchSize\x12J\n" +
	"\x14optional_at_revision\x18\x02 \x01(\v2\x18.authzed.api.v1.ZedTokenR\x12optionalAtRevision\"q\n" +
	"\tBrokenSet\x12#\n" +
	"\rresource_type\x18\x01 \x01(\tR\fresourceType\x12\x1f\n" +
	"\vresource_id\x18\x02 \x01(\tR\n" +
	"resourceId\x12\x1e\n" +
	"\n" +
	"permission\x18\x03 \x01(\tR\n" +
	"permission\"\x96\x01\n" +
	"\x16ReadBrokenSetsResponse\x12F\n" +
	"\vbroken_sets\x18\x01 \x03(\v2%.authzed.api.materialize.v0.BrokenSetR\n" +
	"brokenSets\x124\n" +
	"\brevision\x18\x02 \x01(\v2\x18.authzed.api.v1.ZedTokenR\brevision2\x90\x01\n" +
	"\x11BrokenSetsService\x12{\n" +
	"\x0eReadBrokenSets\x121.authzed.api.materialize.v0.ReadBrokenSetsRequest\x1a2.authzed.api.materialize.v0.ReadBrokenSetsResponse\"\x000\x01Bb\n" +
	"\x1ecom.authzed.api.materialize.v0P\x01Z>github.com/authzed/authzed-go/proto/authzed/api/materialize/v0b\x06proto3"

var (
	file_authzed_api_materialize_v0_brokensets_service_proto_rawDescOnce sync.Once
	file_authzed_api_materialize_v0_brokensets_service_proto_rawDescData []byte
)

func file_authzed_api_materialize_v0_brokensets_service_proto_rawDescGZIP() []byte {
	file_authzed_api_materialize_v0_brokensets_service_proto_rawDescOnce.Do(func() {
		file_authzed_api_materialize_v0_brokensets_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_authzed_api_materialize_v0_brokensets_service_proto_rawDesc), len(file_authzed_api_materialize_v0_brokensets_service_proto_rawDesc)))
	})
	return file_authzed_api_materialize_v0_brokensets_service_proto_rawDescData
}

var file_authzed_api_materialize_v0_brokensets_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_authzed_api_materialize_v0_brokensets_service_proto_goTypes = []any{
	(*ReadBrokenSetsRequest)(nil),  // 0: authzed.api.materialize.v0.ReadBrokenSetsRequest
	(*BrokenSet)(nil),              // 1: authzed.api.materialize.v0.BrokenSet
	(*ReadBrokenSetsResponse)(nil), // 2: authzed.api.materialize.v0.ReadBrokenSetsResponse
	(*v1.ZedToken)(nil),            // 3: authzed.api.v1.ZedToken
}
var file_authzed_api_materialize_v0_brokensets_service_proto_depIdxs = []int32{
	3, // 0: authzed.api.materialize.v0.ReadBrokenSetsRequest.optional_at_revision:type_name -> authzed.api.v1.ZedToken
	1, // 1: authzed.api.materialize.v0.ReadBrokenSetsResponse.broken_sets:type_name -> authzed.api.materialize.v0.BrokenSet
	3, // 2: authzed.api.materialize.v0.ReadBrokenSetsResponse.revision:type_name -> authzed.api.v1.ZedToken
	0, // 3: authzed.api.materialize.v0.BrokenSetsService.ReadBrokenSets:input_type -> authzed.api.materialize.v0.ReadBrokenSetsRequest
	2, // 4: authzed.api.materialize.v0.BrokenSetsService.ReadBrokenSets:output_type -> authzed.api.materialize.v0.ReadBrokenSetsResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_authzed_api_materialize_v0_brokensets_service_proto_init() }
func file_authzed_api_materialize_v0_brokensets_service_proto_init() {
	if File_authzed_api_materialize_v0_brokensets_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_authzed_api_materialize_v0_brokensets_service_proto_rawDesc), len(file_authzed_api_materialize_v0_brokensets_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_authzed_api_materialize_v0_brokensets_service_proto_goTypes,
		DependencyIndexes: file_authzed_api_materialize_v0_brokensets_service_proto_depIdxs,
		MessageInfos:      file_authzed_api_materialize_v0_brokensets_service_proto_msgTypes,
	}.Build()
	File_authzed_api_materialize_v0_brokensets_service_proto = out.File
	file_authzed_api_materialize_v0_brokensets_service_proto_goTypes = nil
	file_authzed_api_materialize_v0_brokensets_service_proto_depIdxs = nil
}
