// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: authzed/api/materialize/v0/brokenpermissions.proto

package v0

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ReadBrokenWatchedPermissionsRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *ReadBrokenWatchedPermissionsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ReadBrokenWatchedPermissionsRequest
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// ReadBrokenWatchedPermissionsRequestMultiError, or nil if none found.
func (m *ReadBrokenWatchedPermissionsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ReadBrokenWatchedPermissionsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetOptionalAtRevision()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ReadBrokenWatchedPermissionsRequestValidationError{
					field:  "OptionalAtRevision",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ReadBrokenWatchedPermissionsRequestValidationError{
					field:  "OptionalAtRevision",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetOptionalAtRevision()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ReadBrokenWatchedPermissionsRequestValidationError{
				field:  "OptionalAtRevision",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ReadBrokenWatchedPermissionsRequestMultiError(errors)
	}

	return nil
}

// ReadBrokenWatchedPermissionsRequestMultiError is an error wrapping multiple
// validation errors returned by
// ReadBrokenWatchedPermissionsRequest.ValidateAll() if the designated
// constraints aren't met.
type ReadBrokenWatchedPermissionsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ReadBrokenWatchedPermissionsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ReadBrokenWatchedPermissionsRequestMultiError) AllErrors() []error { return m }

// ReadBrokenWatchedPermissionsRequestValidationError is the validation error
// returned by ReadBrokenWatchedPermissionsRequest.Validate if the designated
// constraints aren't met.
type ReadBrokenWatchedPermissionsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ReadBrokenWatchedPermissionsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ReadBrokenWatchedPermissionsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ReadBrokenWatchedPermissionsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ReadBrokenWatchedPermissionsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ReadBrokenWatchedPermissionsRequestValidationError) ErrorName() string {
	return "ReadBrokenWatchedPermissionsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ReadBrokenWatchedPermissionsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sReadBrokenWatchedPermissionsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ReadBrokenWatchedPermissionsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ReadBrokenWatchedPermissionsRequestValidationError{}

// Validate checks the field values on ReadBrokenWatchedPermissionsResponse
// with the rules defined in the proto definition for this message. If any
// rules are violated, the first error encountered is returned, or nil if
// there are no violations.
func (m *ReadBrokenWatchedPermissionsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ReadBrokenWatchedPermissionsResponse
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// ReadBrokenWatchedPermissionsResponseMultiError, or nil if none found.
func (m *ReadBrokenWatchedPermissionsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ReadBrokenWatchedPermissionsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetRevision()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ReadBrokenWatchedPermissionsResponseValidationError{
					field:  "Revision",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ReadBrokenWatchedPermissionsResponseValidationError{
					field:  "Revision",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetRevision()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ReadBrokenWatchedPermissionsResponseValidationError{
				field:  "Revision",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetWatchedPermission()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ReadBrokenWatchedPermissionsResponseValidationError{
					field:  "WatchedPermission",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ReadBrokenWatchedPermissionsResponseValidationError{
					field:  "WatchedPermission",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetWatchedPermission()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ReadBrokenWatchedPermissionsResponseValidationError{
				field:  "WatchedPermission",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	for idx, item := range m.GetCycle() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ReadBrokenWatchedPermissionsResponseValidationError{
						field:  fmt.Sprintf("Cycle[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ReadBrokenWatchedPermissionsResponseValidationError{
						field:  fmt.Sprintf("Cycle[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ReadBrokenWatchedPermissionsResponseValidationError{
					field:  fmt.Sprintf("Cycle[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ReadBrokenWatchedPermissionsResponseMultiError(errors)
	}

	return nil
}

// ReadBrokenWatchedPermissionsResponseMultiError is an error wrapping multiple
// validation errors returned by
// ReadBrokenWatchedPermissionsResponse.ValidateAll() if the designated
// constraints aren't met.
type ReadBrokenWatchedPermissionsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ReadBrokenWatchedPermissionsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ReadBrokenWatchedPermissionsResponseMultiError) AllErrors() []error { return m }

// ReadBrokenWatchedPermissionsResponseValidationError is the validation error
// returned by ReadBrokenWatchedPermissionsResponse.Validate if the designated
// constraints aren't met.
type ReadBrokenWatchedPermissionsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ReadBrokenWatchedPermissionsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ReadBrokenWatchedPermissionsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ReadBrokenWatchedPermissionsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ReadBrokenWatchedPermissionsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ReadBrokenWatchedPermissionsResponseValidationError) ErrorName() string {
	return "ReadBrokenWatchedPermissionsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ReadBrokenWatchedPermissionsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sReadBrokenWatchedPermissionsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ReadBrokenWatchedPermissionsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ReadBrokenWatchedPermissionsResponseValidationError{}

// Validate checks the field values on BrokenWatchedPermission with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *BrokenWatchedPermission) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BrokenWatchedPermission with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// BrokenWatchedPermissionMultiError, or nil if none found.
func (m *BrokenWatchedPermission) ValidateAll() error {
	return m.validate(true)
}

func (m *BrokenWatchedPermission) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ResourceType

	// no validation rules for Permission

	if len(errors) > 0 {
		return BrokenWatchedPermissionMultiError(errors)
	}

	return nil
}

// BrokenWatchedPermissionMultiError is an error wrapping multiple validation
// errors returned by BrokenWatchedPermission.ValidateAll() if the designated
// constraints aren't met.
type BrokenWatchedPermissionMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BrokenWatchedPermissionMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BrokenWatchedPermissionMultiError) AllErrors() []error { return m }

// BrokenWatchedPermissionValidationError is the validation error returned by
// BrokenWatchedPermission.Validate if the designated constraints aren't met.
type BrokenWatchedPermissionValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BrokenWatchedPermissionValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BrokenWatchedPermissionValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BrokenWatchedPermissionValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BrokenWatchedPermissionValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BrokenWatchedPermissionValidationError) ErrorName() string {
	return "BrokenWatchedPermissionValidationError"
}

// Error satisfies the builtin error interface
func (e BrokenWatchedPermissionValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBrokenWatchedPermission.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BrokenWatchedPermissionValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BrokenWatchedPermissionValidationError{}

// Validate checks the field values on Resource with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Resource) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Resource with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ResourceMultiError, or nil
// if none found.
func (m *Resource) ValidateAll() error {
	return m.validate(true)
}

func (m *Resource) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ObjectType

	// no validation rules for ObjectId

	// no validation rules for PermissionOrRelation

	if len(errors) > 0 {
		return ResourceMultiError(errors)
	}

	return nil
}

// ResourceMultiError is an error wrapping multiple validation errors returned
// by Resource.ValidateAll() if the designated constraints aren't met.
type ResourceMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ResourceMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ResourceMultiError) AllErrors() []error { return m }

// ResourceValidationError is the validation error returned by
// Resource.Validate if the designated constraints aren't met.
type ResourceValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ResourceValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ResourceValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ResourceValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ResourceValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ResourceValidationError) ErrorName() string { return "ResourceValidationError" }

// Error satisfies the builtin error interface
func (e ResourceValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sResource.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ResourceValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ResourceValidationError{}
