// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: authzed/api/materialize/v0/roaringlookupresources.proto

package v0

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v1 "github.com/authzed/authzed-go/proto/authzed/api/v1"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExperimentalRoaringLookupResourcesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// consistency selects the snapshot at which the lookup is performed. If
	// unspecified, minimize_latency is used.
	Consistency *v1.Consistency `protobuf:"bytes,1,opt,name=consistency,proto3" json:"consistency,omitempty"`
	// resource_object_type is the type of resource over which to look up access.
	ResourceObjectType string `protobuf:"bytes,2,opt,name=resource_object_type,json=resourceObjectType,proto3" json:"resource_object_type,omitempty"`
	// permission is the name of the permission or relation to look up.
	Permission string `protobuf:"bytes,3,opt,name=permission,proto3" json:"permission,omitempty"`
	// subject is the subject for which access is being looked up.
	Subject       *v1.SubjectReference `protobuf:"bytes,4,opt,name=subject,proto3" json:"subject,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExperimentalRoaringLookupResourcesRequest) Reset() {
	*x = ExperimentalRoaringLookupResourcesRequest{}
	mi := &file_authzed_api_materialize_v0_roaringlookupresources_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExperimentalRoaringLookupResourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExperimentalRoaringLookupResourcesRequest) ProtoMessage() {}

func (x *ExperimentalRoaringLookupResourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authzed_api_materialize_v0_roaringlookupresources_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExperimentalRoaringLookupResourcesRequest.ProtoReflect.Descriptor instead.
func (*ExperimentalRoaringLookupResourcesRequest) Descriptor() ([]byte, []int) {
	return file_authzed_api_materialize_v0_roaringlookupresources_proto_rawDescGZIP(), []int{0}
}

func (x *ExperimentalRoaringLookupResourcesRequest) GetConsistency() *v1.Consistency {
	if x != nil {
		return x.Consistency
	}
	return nil
}

func (x *ExperimentalRoaringLookupResourcesRequest) GetResourceObjectType() string {
	if x != nil {
		return x.ResourceObjectType
	}
	return ""
}

func (x *ExperimentalRoaringLookupResourcesRequest) GetPermission() string {
	if x != nil {
		return x.Permission
	}
	return ""
}

func (x *ExperimentalRoaringLookupResourcesRequest) GetSubject() *v1.SubjectReference {
	if x != nil {
		return x.Subject
	}
	return nil
}

type ExperimentalRoaringLookupResourcesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// bitmap is the roaring64 bitmap, in RoaringFormatSpec 64-bit portable
	// format, of the resource object IDs accessible to the subject. The IDs are
	// the object IDs from the relationships themselves, as 44-bit integers.
	Bitmap []byte `protobuf:"bytes,1,opt,name=bitmap,proto3" json:"bitmap,omitempty"`
	// cardinality is the number of resource IDs in the bitmap.
	Cardinality uint64 `protobuf:"varint,2,opt,name=cardinality,proto3" json:"cardinality,omitempty"`
	// at_revision is the ZedToken at which the lookup was performed.
	AtRevision    *v1.ZedToken `protobuf:"bytes,3,opt,name=at_revision,json=atRevision,proto3" json:"at_revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExperimentalRoaringLookupResourcesResponse) Reset() {
	*x = ExperimentalRoaringLookupResourcesResponse{}
	mi := &file_authzed_api_materialize_v0_roaringlookupresources_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExperimentalRoaringLookupResourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExperimentalRoaringLookupResourcesResponse) ProtoMessage() {}

func (x *ExperimentalRoaringLookupResourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authzed_api_materialize_v0_roaringlookupresources_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExperimentalRoaringLookupResourcesResponse.ProtoReflect.Descriptor instead.
func (*ExperimentalRoaringLookupResourcesResponse) Descriptor() ([]byte, []int) {
	return file_authzed_api_materialize_v0_roaringlookupresources_proto_rawDescGZIP(), []int{1}
}

func (x *ExperimentalRoaringLookupResourcesResponse) GetBitmap() []byte {
	if x != nil {
		return x.Bitmap
	}
	return nil
}

func (x *ExperimentalRoaringLookupResourcesResponse) GetCardinality() uint64 {
	if x != nil {
		return x.Cardinality
	}
	return 0
}

func (x *ExperimentalRoaringLookupResourcesResponse) GetAtRevision() *v1.ZedToken {
	if x != nil {
		return x.AtRevision
	}
	return nil
}

var File_authzed_api_materialize_v0_roaringlookupresources_proto protoreflect.FileDescriptor

const file_authzed_api_materialize_v0_roaringlookupresources_proto_rawDesc = "" +
	"\n" +
	"7authzed/api/materialize/v0/roaringlookupresources.proto\x12\x1aauthzed.api.materialize.v0\x1a\x19authzed/api/v1/core.proto\x1a'authzed/api/v1/permission_service.proto\x1a\x1bbuf/validate/validate.proto\x1a\x17validate/validate.proto\"\xec\x03\n" +
	")ExperimentalRoaringLookupResourcesRequest\x12=\n" +
	"\vconsistency\x18\x01 \x01(\v2\x1b.authzed.api.v1.ConsistencyR\vconsistency\x12\xc3\x01\n" +
	"\x14resource_object_type\x18\x02 \x01(\tB\x90\x01\xfaBErC(\x80\x012>^([a-z][a-z0-9_]{1,61}[a-z0-9]/)*[a-z][a-z0-9_]{1,62}[a-z0-9]$\xbaHErC(\x80\x012>^([a-z][a-z0-9_]{1,61}[a-z0-9]/)*[a-z][a-z0-9_]{1,62}[a-z0-9]$R\x12resourceObjectType\x12n\n" +
	"\n" +
	"permission\x18\x03 \x01(\tBN\xfaB$r\"(@2\x1e^[a-z][a-z0-9_]{1,62}[a-z0-9]$\xbaH$r\"(@2\x1e^[a-z][a-z0-9_]{1,62}[a-z0-9]$R\n" +
	"permission\x12J\n" +
	"\asubject\x18\x04 \x01(\v2 .authzed.api.v1.SubjectReferenceB\x0e\xfaB\x05\x8a\x01\x02\x10\x01\xbaH\x03\xc8\x01\x01R\asubject\"\xb1\x01\n" +
	"*ExperimentalRoaringLookupResourcesResponse\x12\x16\n" +
	"\x06bitmap\x18\x01 \x01(\fR\x06bitmap\x12 \n" +
	"\vcardinality\x18\x02 \x01(\x04R\vcardinality\x12I\n" +
	"\vat_revision\x18\x03 \x01(\v2\x18.authzed.api.v1.ZedTokenB\x0e\xfaB\x05\x8a\x01\x02\x10\x01\xbaH\x03\xc8\x01\x01R\n" +
	"atRevision2\xd7\x01\n" +
	"\x1dRoaringLookupResourcesService\x12\xb5\x01\n" +
	"\"ExperimentalRoaringLookupResources\x12E.authzed.api.materialize.v0.ExperimentalRoaringLookupResourcesRequest\x1aF.authzed.api.materialize.v0.ExperimentalRoaringLookupResourcesResponse\"\x00Bb\n" +
	"\x1ecom.authzed.api.materialize.v0P\x01Z>github.com/authzed/authzed-go/proto/authzed/api/materialize/v0b\x06proto3"

var (
	file_authzed_api_materialize_v0_roaringlookupresources_proto_rawDescOnce sync.Once
	file_authzed_api_materialize_v0_roaringlookupresources_proto_rawDescData []byte
)

func file_authzed_api_materialize_v0_roaringlookupresources_proto_rawDescGZIP() []byte {
	file_authzed_api_materialize_v0_roaringlookupresources_proto_rawDescOnce.Do(func() {
		file_authzed_api_materialize_v0_roaringlookupresources_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_authzed_api_materialize_v0_roaringlookupresources_proto_rawDesc), len(file_authzed_api_materialize_v0_roaringlookupresources_proto_rawDesc)))
	})
	return file_authzed_api_materialize_v0_roaringlookupresources_proto_rawDescData
}

var file_authzed_api_materialize_v0_roaringlookupresources_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_authzed_api_materialize_v0_roaringlookupresources_proto_goTypes = []any{
	(*ExperimentalRoaringLookupResourcesRequest)(nil),  // 0: authzed.api.materialize.v0.ExperimentalRoaringLookupResourcesRequest
	(*ExperimentalRoaringLookupResourcesResponse)(nil), // 1: authzed.api.materialize.v0.ExperimentalRoaringLookupResourcesResponse
	(*v1.Consistency)(nil),                             // 2: authzed.api.v1.Consistency
	(*v1.SubjectReference)(nil),                        // 3: authzed.api.v1.SubjectReference
	(*v1.ZedToken)(nil),                                // 4: authzed.api.v1.ZedToken
}
var file_authzed_api_materialize_v0_roaringlookupresources_proto_depIdxs = []int32{
	2, // 0: authzed.api.materialize.v0.ExperimentalRoaringLookupResourcesRequest.consistency:type_name -> authzed.api.v1.Consistency
	3, // 1: authzed.api.materialize.v0.ExperimentalRoaringLookupResourcesRequest.subject:type_name -> authzed.api.v1.SubjectReference
	4, // 2: authzed.api.materialize.v0.ExperimentalRoaringLookupResourcesResponse.at_revision:type_name -> authzed.api.v1.ZedToken
	0, // 3: authzed.api.materialize.v0.RoaringLookupResourcesService.ExperimentalRoaringLookupResources:input_type -> authzed.api.materialize.v0.ExperimentalRoaringLookupResourcesRequest
	1, // 4: authzed.api.materialize.v0.RoaringLookupResourcesService.ExperimentalRoaringLookupResources:output_type -> authzed.api.materialize.v0.ExperimentalRoaringLookupResourcesResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_authzed_api_materialize_v0_roaringlookupresources_proto_init() }
func file_authzed_api_materialize_v0_roaringlookupresources_proto_init() {
	if File_authzed_api_materialize_v0_roaringlookupresources_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_authzed_api_materialize_v0_roaringlookupresources_proto_rawDesc), len(file_authzed_api_materialize_v0_roaringlookupresources_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_authzed_api_materialize_v0_roaringlookupresources_proto_goTypes,
		DependencyIndexes: file_authzed_api_materialize_v0_roaringlookupresources_proto_depIdxs,
		MessageInfos:      file_authzed_api_materialize_v0_roaringlookupresources_proto_msgTypes,
	}.Build()
	File_authzed_api_materialize_v0_roaringlookupresources_proto = out.File
	file_authzed_api_materialize_v0_roaringlookupresources_proto_goTypes = nil
	file_authzed_api_materialize_v0_roaringlookupresources_proto_depIdxs = nil
}
