// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: authzed/api/materialize/v0/stats.proto

package v0

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ExperimentalCountLookupResourcesRequest
// with the rules defined in the proto definition for this message. If any
// rules are violated, the first error encountered is returned, or nil if
// there are no violations.
func (m *ExperimentalCountLookupResourcesRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on
// ExperimentalCountLookupResourcesRequest with the rules defined in the proto
// definition for this message. If any rules are violated, the result is a
// list of violation errors wrapped in
// ExperimentalCountLookupResourcesRequestMultiError, or nil if none found.
func (m *ExperimentalCountLookupResourcesRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ExperimentalCountLookupResourcesRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ResourceObjectType

	// no validation rules for Permission

	if all {
		switch v := interface{}(m.GetSubject()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ExperimentalCountLookupResourcesRequestValidationError{
					field:  "Subject",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ExperimentalCountLookupResourcesRequestValidationError{
					field:  "Subject",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSubject()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ExperimentalCountLookupResourcesRequestValidationError{
				field:  "Subject",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ExperimentalCountLookupResourcesRequestMultiError(errors)
	}

	return nil
}

// ExperimentalCountLookupResourcesRequestMultiError is an error wrapping
// multiple validation errors returned by
// ExperimentalCountLookupResourcesRequest.ValidateAll() if the designated
// constraints aren't met.
type ExperimentalCountLookupResourcesRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ExperimentalCountLookupResourcesRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ExperimentalCountLookupResourcesRequestMultiError) AllErrors() []error { return m }

// ExperimentalCountLookupResourcesRequestValidationError is the validation
// error returned by ExperimentalCountLookupResourcesRequest.Validate if the
// designated constraints aren't met.
type ExperimentalCountLookupResourcesRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ExperimentalCountLookupResourcesRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ExperimentalCountLookupResourcesRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ExperimentalCountLookupResourcesRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ExperimentalCountLookupResourcesRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ExperimentalCountLookupResourcesRequestValidationError) ErrorName() string {
	return "ExperimentalCountLookupResourcesRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ExperimentalCountLookupResourcesRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sExperimentalCountLookupResourcesRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ExperimentalCountLookupResourcesRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ExperimentalCountLookupResourcesRequestValidationError{}

// Validate checks the field values on ExperimentalCountLookupResourcesResponse
// with the rules defined in the proto definition for this message. If any
// rules are violated, the first error encountered is returned, or nil if
// there are no violations.
func (m *ExperimentalCountLookupResourcesResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on
// ExperimentalCountLookupResourcesResponse with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in
// ExperimentalCountLookupResourcesResponseMultiError, or nil if none found.
func (m *ExperimentalCountLookupResourcesResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ExperimentalCountLookupResourcesResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ResourceCount

	if all {
		switch v := interface{}(m.GetReadAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ExperimentalCountLookupResourcesResponseValidationError{
					field:  "ReadAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ExperimentalCountLookupResourcesResponseValidationError{
					field:  "ReadAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetReadAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ExperimentalCountLookupResourcesResponseValidationError{
				field:  "ReadAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ExperimentalCountLookupResourcesResponseMultiError(errors)
	}

	return nil
}

// ExperimentalCountLookupResourcesResponseMultiError is an error wrapping
// multiple validation errors returned by
// ExperimentalCountLookupResourcesResponse.ValidateAll() if the designated
// constraints aren't met.
type ExperimentalCountLookupResourcesResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ExperimentalCountLookupResourcesResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ExperimentalCountLookupResourcesResponseMultiError) AllErrors() []error { return m }

// ExperimentalCountLookupResourcesResponseValidationError is the validation
// error returned by ExperimentalCountLookupResourcesResponse.Validate if the
// designated constraints aren't met.
type ExperimentalCountLookupResourcesResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ExperimentalCountLookupResourcesResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ExperimentalCountLookupResourcesResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ExperimentalCountLookupResourcesResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ExperimentalCountLookupResourcesResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ExperimentalCountLookupResourcesResponseValidationError) ErrorName() string {
	return "ExperimentalCountLookupResourcesResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ExperimentalCountLookupResourcesResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sExperimentalCountLookupResourcesResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ExperimentalCountLookupResourcesResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ExperimentalCountLookupResourcesResponseValidationError{}

// Validate checks the field values on ExperimentalCountLookupSubjectsRequest
// with the rules defined in the proto definition for this message. If any
// rules are violated, the first error encountered is returned, or nil if
// there are no violations.
func (m *ExperimentalCountLookupSubjectsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on
// ExperimentalCountLookupSubjectsRequest with the rules defined in the proto
// definition for this message. If any rules are violated, the result is a
// list of violation errors wrapped in
// ExperimentalCountLookupSubjectsRequestMultiError, or nil if none found.
func (m *ExperimentalCountLookupSubjectsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ExperimentalCountLookupSubjectsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetResource()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ExperimentalCountLookupSubjectsRequestValidationError{
					field:  "Resource",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ExperimentalCountLookupSubjectsRequestValidationError{
					field:  "Resource",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetResource()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ExperimentalCountLookupSubjectsRequestValidationError{
				field:  "Resource",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Permission

	// no validation rules for SubjectObjectType

	// no validation rules for OptionalSubjectRelation

	if len(errors) > 0 {
		return ExperimentalCountLookupSubjectsRequestMultiError(errors)
	}

	return nil
}

// ExperimentalCountLookupSubjectsRequestMultiError is an error wrapping
// multiple validation errors returned by
// ExperimentalCountLookupSubjectsRequest.ValidateAll() if the designated
// constraints aren't met.
type ExperimentalCountLookupSubjectsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ExperimentalCountLookupSubjectsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ExperimentalCountLookupSubjectsRequestMultiError) AllErrors() []error { return m }

// ExperimentalCountLookupSubjectsRequestValidationError is the validation
// error returned by ExperimentalCountLookupSubjectsRequest.Validate if the
// designated constraints aren't met.
type ExperimentalCountLookupSubjectsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ExperimentalCountLookupSubjectsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ExperimentalCountLookupSubjectsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ExperimentalCountLookupSubjectsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ExperimentalCountLookupSubjectsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ExperimentalCountLookupSubjectsRequestValidationError) ErrorName() string {
	return "ExperimentalCountLookupSubjectsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ExperimentalCountLookupSubjectsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sExperimentalCountLookupSubjectsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ExperimentalCountLookupSubjectsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ExperimentalCountLookupSubjectsRequestValidationError{}

// Validate checks the field values on ExperimentalCountLookupSubjectsResponse
// with the rules defined in the proto definition for this message. If any
// rules are violated, the first error encountered is returned, or nil if
// there are no violations.
func (m *ExperimentalCountLookupSubjectsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on
// ExperimentalCountLookupSubjectsResponse with the rules defined in the proto
// definition for this message. If any rules are violated, the result is a
// list of violation errors wrapped in
// ExperimentalCountLookupSubjectsResponseMultiError, or nil if none found.
func (m *ExperimentalCountLookupSubjectsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ExperimentalCountLookupSubjectsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for SubjectCount

	if all {
		switch v := interface{}(m.GetReadAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ExperimentalCountLookupSubjectsResponseValidationError{
					field:  "ReadAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ExperimentalCountLookupSubjectsResponseValidationError{
					field:  "ReadAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetReadAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ExperimentalCountLookupSubjectsResponseValidationError{
				field:  "ReadAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ExperimentalCountLookupSubjectsResponseMultiError(errors)
	}

	return nil
}

// ExperimentalCountLookupSubjectsResponseMultiError is an error wrapping
// multiple validation errors returned by
// ExperimentalCountLookupSubjectsResponse.ValidateAll() if the designated
// constraints aren't met.
type ExperimentalCountLookupSubjectsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ExperimentalCountLookupSubjectsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ExperimentalCountLookupSubjectsResponseMultiError) AllErrors() []error { return m }

// ExperimentalCountLookupSubjectsResponseValidationError is the validation
// error returned by ExperimentalCountLookupSubjectsResponse.Validate if the
// designated constraints aren't met.
type ExperimentalCountLookupSubjectsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ExperimentalCountLookupSubjectsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ExperimentalCountLookupSubjectsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ExperimentalCountLookupSubjectsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ExperimentalCountLookupSubjectsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ExperimentalCountLookupSubjectsResponseValidationError) ErrorName() string {
	return "ExperimentalCountLookupSubjectsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ExperimentalCountLookupSubjectsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sExperimentalCountLookupSubjectsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ExperimentalCountLookupSubjectsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ExperimentalCountLookupSubjectsResponseValidationError{}
