// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: authzed/api/v0/core.proto

package v0

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RelationTuple struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Each tupleset specifies keys of a set of relation tuples. The set can
	// include a single tuple key, or all tuples with a given object ID or
	// userset in a namespace, optionally constrained by a relation name.
	//
	// examples:
	// doc:readme#viewer@group:eng#member (fully specified)
	// doc:*#*#group:eng#member (all tuples that this userset relates to)
	// doc:12345#*#* (all tuples with a direct relationship to a document)
	// doc:12345#writer#* (all tuples with direct write relationship with the
	// document) doc:#writer#group:eng#member (all tuples that eng group has write
	// relationship)
	ObjectAndRelation *ObjectAndRelation `protobuf:"bytes,1,opt,name=object_and_relation,json=objectAndRelation,proto3" json:"object_and_relation,omitempty"`
	User              *User              `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RelationTuple) Reset() {
	*x = RelationTuple{}
	mi := &file_authzed_api_v0_core_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelationTuple) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationTuple) ProtoMessage() {}

func (x *RelationTuple) ProtoReflect() protoreflect.Message {
	mi := &file_authzed_api_v0_core_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationTuple.ProtoReflect.Descriptor instead.
func (*RelationTuple) Descriptor() ([]byte, []int) {
	return file_authzed_api_v0_core_proto_rawDescGZIP(), []int{0}
}

func (x *RelationTuple) GetObjectAndRelation() *ObjectAndRelation {
	if x != nil {
		return x.ObjectAndRelation
	}
	return nil
}

func (x *RelationTuple) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type ObjectAndRelation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ObjectId      string                 `protobuf:"bytes,2,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	Relation      string                 `protobuf:"bytes,3,opt,name=relation,proto3" json:"relation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectAndRelation) Reset() {
	*x = ObjectAndRelation{}
	mi := &file_authzed_api_v0_core_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectAndRelation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectAndRelation) ProtoMessage() {}

func (x *ObjectAndRelation) ProtoReflect() protoreflect.Message {
	mi := &file_authzed_api_v0_core_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectAndRelation.ProtoReflect.Descriptor instead.
func (*ObjectAndRelation) Descriptor() ([]byte, []int) {
	return file_authzed_api_v0_core_proto_rawDescGZIP(), []int{1}
}

func (x *ObjectAndRelation) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ObjectAndRelation) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *ObjectAndRelation) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

type RelationReference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Relation      string                 `protobuf:"bytes,3,opt,name=relation,proto3" json:"relation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelationReference) Reset() {
	*x = RelationReference{}
	mi := &file_authzed_api_v0_core_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelationReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationReference) ProtoMessage() {}

func (x *RelationReference) ProtoReflect() protoreflect.Message {
	mi := &file_authzed_api_v0_core_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationReference.ProtoReflect.Descriptor instead.
func (*RelationReference) Descriptor() ([]byte, []int) {
	return file_authzed_api_v0_core_proto_rawDescGZIP(), []int{2}
}

func (x *RelationReference) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *RelationReference) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

type User struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to UserOneof:
	//
	//	*User_Userset
	UserOneof     isUser_UserOneof `protobuf_oneof:"user_oneof"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_authzed_api_v0_core_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_authzed_api_v0_core_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_authzed_api_v0_core_proto_rawDescGZIP(), []int{3}
}

func (x *User) GetUserOneof() isUser_UserOneof {
	if x != nil {
		return x.UserOneof
	}
	return nil
}

func (x *User) GetUserset() *ObjectAndRelation {
	if x != nil {
		if x, ok := x.UserOneof.(*User_Userset); ok {
			return x.Userset
		}
	}
	return nil
}

type isUser_UserOneof interface {
	isUser_UserOneof()
}

type User_Userset struct {
	Userset *ObjectAndRelation `protobuf:"bytes,2,opt,name=userset,proto3,oneof"`
}

func (*User_Userset) isUser_UserOneof() {}

var File_authzed_api_v0_core_proto protoreflect.FileDescriptor

const file_authzed_api_v0_core_proto_rawDesc = "" +
	"\n" +
	"\x19authzed/api/v0/core.proto\x12\x0eauthzed.api.v0\x1a\x17validate/validate.proto\"\xa0\x01\n" +
	"\rRelationTuple\x12[\n" +
	"\x13object_and_relation\x18\x01 \x01(\v2!.authzed.api.v0.ObjectAndRelationB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x11objectAndRelation\x122\n" +
	"\x04user\x18\x02 \x01(\v2\x14.authzed.api.v0.UserB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x04user\"\x9d\x02\n" +
	"\x11ObjectAndRelation\x12f\n" +
	"\tnamespace\x18\x01 \x01(\tBH\xfaBErC(\x80\x012>^([a-z][a-z0-9_]{1,61}[a-z0-9]/)?[a-z][a-z0-9_]{1,62}[a-z0-9]$R\tnamespace\x12R\n" +
	"\tobject_id\x18\x02 \x01(\tB5\xfaB2r0(\x80\x012+^(([a-zA-Z0-9_][a-zA-Z0-9/_|-]{0,127})|\\*)$R\bobjectId\x12L\n" +
	"\brelation\x18\x03 \x01(\tB0\xfaB-r+(@2'^(\\.\\.\\.|[a-z][a-z0-9_]{1,62}[a-z0-9])$R\brelation\"\xc9\x01\n" +
	"\x11RelationReference\x12f\n" +
	"\tnamespace\x18\x01 \x01(\tBH\xfaBErC(\x80\x012>^([a-z][a-z0-9_]{1,61}[a-z0-9]/)?[a-z][a-z0-9_]{1,62}[a-z0-9]$R\tnamespace\x12L\n" +
	"\brelation\x18\x03 \x01(\tB0\xfaB-r+(@2'^(\\.\\.\\.|[a-z][a-z0-9_]{1,62}[a-z0-9])$R\brelation\"b\n" +
	"\x04User\x12G\n" +
	"\auserset\x18\x02 \x01(\v2!.authzed.api.v0.ObjectAndRelationB\b\xfaB\x05\x8a\x01\x02\x10\x01H\x00R\ausersetB\x11\n" +
	"\n" +
	"user_oneof\x12\x03\xf8B\x01BH\n" +
	"\x12com.authzed.api.v0Z2github.com/authzed/authzed-go/proto/authzed/api/v0b\x06proto3"

var (
	file_authzed_api_v0_core_proto_rawDescOnce sync.Once
	file_authzed_api_v0_core_proto_rawDescData []byte
)

func file_authzed_api_v0_core_proto_rawDescGZIP() []byte {
	file_authzed_api_v0_core_proto_rawDescOnce.Do(func() {
		file_authzed_api_v0_core_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_authzed_api_v0_core_proto_rawDesc), len(file_authzed_api_v0_core_proto_rawDesc)))
	})
	return file_authzed_api_v0_core_proto_rawDescData
}

var file_authzed_api_v0_core_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_authzed_api_v0_core_proto_goTypes = []any{
	(*RelationTuple)(nil),     // 0: authzed.api.v0.RelationTuple
	(*ObjectAndRelation)(nil), // 1: authzed.api.v0.ObjectAndRelation
	(*RelationReference)(nil), // 2: authzed.api.v0.RelationReference
	(*User)(nil),              // 3: authzed.api.v0.User
}
var file_authzed_api_v0_core_proto_depIdxs = []int32{
	1, // 0: authzed.api.v0.RelationTuple.object_and_relation:type_name -> authzed.api.v0.ObjectAndRelation
	3, // 1: authzed.api.v0.RelationTuple.user:type_name -> authzed.api.v0.User
	1, // 2: authzed.api.v0.User.userset:type_name -> authzed.api.v0.ObjectAndRelation
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_authzed_api_v0_core_proto_init() }
func file_authzed_api_v0_core_proto_init() {
	if File_authzed_api_v0_core_proto != nil {
		return
	}
	file_authzed_api_v0_core_proto_msgTypes[3].OneofWrappers = []any{
		(*User_Userset)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_authzed_api_v0_core_proto_rawDesc), len(file_authzed_api_v0_core_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_authzed_api_v0_core_proto_goTypes,
		DependencyIndexes: file_authzed_api_v0_core_proto_depIdxs,
		MessageInfos:      file_authzed_api_v0_core_proto_msgTypes,
	}.Build()
	File_authzed_api_v0_core_proto = out.File
	file_authzed_api_v0_core_proto_goTypes = nil
	file_authzed_api_v0_core_proto_depIdxs = nil
}
