---
run:
  timeout: "5m"
issues:
  exclude-dirs:
    - "proto"
output:
  sort-results: true
linters-settings:
  goimports:
    local-prefixes: "github.com/authzed/authzed-go"
  revive:
    rules:
      - name: "unused-parameter"
        disabled: true
  gosec:
    excludes:
      - "G402"  # Allow users to configure InsecureSkipVerify
linters:
  enable:
    - "bidichk"
    - "bodyclose"
    - "errcheck"
    - "errname"
    - "errorlint"
    - "gofumpt"
    - "goimports"
    - "goprintffuncname"
    - "gosec"
    - "gosimple"
    - "govet"
    - "importas"
    - "ineffassign"
    - "makezero"
    - "paralleltest"
    - "prealloc"
    - "predeclared"
    - "promlinter"
    - "revive"
    - "rowserrcheck"
    - "staticcheck"
    - "stylecheck"
    - "tenv"
    - "typecheck"
    - "unconvert"
    - "unused"
    - "wastedassign"
    - "whitespace"
