---
name: "CLA"
on:
  issue_comment:
    types:
      - "created"
  pull_request_target:
    types:
      - "opened"
      - "closed"
      - "synchronize"

jobs:
  CLAssistant:
    name: "Check for Signature"
    runs-on: "ubuntu-latest"
    steps:
      - name: "CLA Assistant"
        if: "(github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'"
        uses: "cla-assistant/github-action@v2.1.3-beta"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          PERSONAL_ACCESS_TOKEN: "${{ secrets.CLA_ASSISTANT_ACCESS_TOKEN }}"
        with:
          remote-organization-name: "authzed"
          remote-repository-name: "cla"
          path-to-signatures: "v1/signatures.json"
          path-to-document: "https://github.com/authzed/cla/blob/main/v1/icla.md"
          branch: "main"
          allowlist: "authzedbot,dependabot[bot]"
